on:
  schedule:
    # monthly
    - cron: "0 0 1 * *"

  # run if user manually requests it
  workflow_dispatch:

name: Broken Link Check
jobs:
  broken-link-check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Broken Link Check
        uses: technote-space/broken-link-checker-action@v2
        with:
          TARGET: https://mf1-btr.github.io/
          RECURSIVE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
